In [1]:
import pandas as pd
import numpy as np

In [2]:
name_age={"Yiğit" : 16,"Joseph" : 79, "Giorno" : 18}

In [3]:
pd.Series(name_age)

Yiğit     16
Joseph    79
Giorno    18
dtype: int64

In [4]:
name_list=["Yiğit","Joseph","Giorno"]
age_list=[16,79,18]

In [5]:
pd.Series(age_list,name_list)

Yiğit     16
Joseph    79
Giorno    18
dtype: int64

In [6]:
pd.Series(index=name_list,data=age_list)

Yiğit     16
Joseph    79
Giorno    18
dtype: int64

In [7]:
bişisler=np.arange(0,10)

In [8]:
bişisler

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
pd.Series(bişisler)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [10]:
yeni_bişisiler=np.array([20,9,19,99])

In [11]:
pd.Series(yeni_bişisiler)

0    20
1     9
2    19
3    99
dtype: int64

In [12]:
my_series=pd.Series(data=age_list,index=name_list)

In [13]:
my_series

Yiğit     16
Joseph    79
Giorno    18
dtype: int64

In [14]:
type(my_series)

pandas.core.series.Series

In [15]:
my_series["Joseph"]

np.int64(79)

In [16]:
my_series["Joseph"] = 89

In [17]:
my_series

Yiğit     16
Joseph    89
Giorno    18
dtype: int64

In [18]:
my_data=np.array([[10,20,30],[9,998,90],[11,12,23]])

In [19]:
my_data

array([[ 10,  20,  30],
       [  9, 998,  90],
       [ 11,  12,  23]])

In [20]:
isimler=["Yiğit","Johnny","Edward"]

In [21]:
buişiler=["January","February","April"]

In [22]:
data_frame=pd.DataFrame(my_data, index=isimler, columns=buişiler)

In [23]:
data_frame

        January  February  April
Yiğit        10        20     30
Johnny        9       998     90
Edward       11        12     23

In [24]:
feb_series=data_frame["February"]

In [25]:
feb_series

Yiğit      20
Johnny    998
Edward     12
Name: February, dtype: int64

In [26]:
feb_series.mean()

np.float64(343.3333333333333)

In [27]:
feb_series.max()

998

In [28]:
data_frame["August"]=data_frame["April"]*2

In [29]:
data_frame

        January  February  April  August
Yiğit        10        20     30      60
Johnny        9       998     90     180
Edward       11        12     23      46

In [30]:
data_frame.drop("Johnny",axis=0)

        January  February  April  August
Yiğit        10        20     30      60
Edward       11        12     23      46

In [31]:
data_frame.drop("August",axis=1)

        January  February  April
Yiğit        10        20     30
Johnny        9       998     90
Edward       11        12     23

In [32]:
data_frame

        January  February  April  August
Yiğit        10        20     30      60
Johnny        9       998     90     180
Edward       11        12     23      46

In [33]:
data_frame.drop("August",axis=1,inplace=True)

In [34]:
data_frame

        January  February  April
Yiğit        10        20     30
Johnny        9       998     90
Edward       11        12     23

In [35]:
büyük_list=data_frame>19

In [36]:
büyük_list

        January  February  April
Yiğit     False      True   True
Johnny    False      True   True
Edward    False     False   True

In [37]:
data_frame[büyük_list]

        January  February  April
Yiğit       NaN      20.0     30
Johnny      NaN     998.0     90
Edward      NaN       NaN     23

In [38]:
my_dict={"Yiğit": [40,30,np.nan],"Johnny": [20,np.nan,30],"Edward": [10,20,30]}

In [39]:
my_dict

{'Yiğit': [40, 30, nan], 'Johnny': [20, nan, 30], 'Edward': [10, 20, 30]}

In [40]:
duta_frame=pd.DataFrame(my_dict)

In [41]:
duta_frame

   Yiğit  Johnny  Edward
0   40.0    20.0      10
1   30.0     NaN      20
2    NaN    30.0      30

In [42]:
duta_frame.dropna()

   Yiğit  Johnny  Edward
0   40.0    20.0      10

In [43]:
my_new_dict={"Yiğit": [40,30,np.nan],"Johnny": [20,np.nan,30],"Edward": [10,20,30],"Joesph":[10,np.nan,np.nan]}

In [44]:
new_duta_frame=pd.DataFrame(my_new_dict)

In [45]:
new_duta_frame

   Yiğit  Johnny  Edward  Joesph
0   40.0    20.0      10    10.0
1   30.0     NaN      20     NaN
2    NaN    30.0      30     NaN

In [46]:
new_duta_frame.dropna(axis=1,thresh=2)

   Yiğit  Johnny  Edward
0   40.0    20.0      10
1   30.0     NaN      20
2    NaN    30.0      30

In [47]:
new_duta_frame.fillna(9)

   Yiğit  Johnny  Edward  Joesph
0   40.0    20.0      10    10.0
1   30.0     9.0      20     9.0
2    9.0    30.0      30     9.0

In [48]:
salary_dict = {"Programming Language" : ["Python","Python","Python","Java","Java","Swift"], "Name" : ["A","B","C","D","E","F"], "Salary" : [100,90,80,70,60,50]}

In [49]:
salary_frame=pd.DataFrame(salary_dict)

In [50]:
salary_frame

  Programming Language Name  Salary
0               Python    A     100
1               Python    B      90
2               Python    C      80
3                 Java    D      70
4                 Java    E      60
5                Swift    F      50

In [61]:
group=salary_frame.groupby("Programming Language")

In [62]:
group.count()

                      Name  Salary
Programming Language
Java                     2       2
Python                   3       3
Swift                    1       1

In [63]:
group.min("Salary")

                      Salary
Programming Language
Java                      60
Python                    80
Swift                     50

In [64]:
group.mean("Salary")

                      Salary
Programming Language
Java                    65.0
Python                  90.0
Swift                   50.0

In [65]:
group.describe()

                     Salary
                      count  mean        std   min   25%   50%   75%    max
Programming Language
Java                    2.0  65.0   7.071068  60.0  62.5  65.0  67.5   70.0
Python                  3.0  90.0  10.000000  80.0  85.0  90.0  95.0  100.0
Swift                   1.0  50.0        NaN  50.0  50.0  50.0  50.0   50.0

In [87]:
my_dicti1 = {"Name" : ["A","B","C","D"],
           "Sports" : ["Basketball", "Football", "Tennis", "Running"],
            "Calories" : [100,200,300,400]
           }

In [88]:
frameinho=pd.DataFrame(my_dicti1)

In [89]:
frameinho

  Name      Sports  Calories
0    A  Basketball       100
1    B    Football       200
2    C      Tennis       300
3    D     Running       400

In [97]:
my_dicti2 = {"Name" : ["E","Z","Y","N"],
           "Sports" : ["Basketball", "Football", "Tennis", "Running"],
            "Calories" : [150,290,310,200]
           }

In [98]:
frameinho2=pd.DataFrame(my_dicti2)

In [99]:
frameinho2

  Name      Sports  Calories
0    E  Basketball       150
1    Z    Football       290
2    Y      Tennis       310
3    N     Running       200

In [100]:
my_dicti3 = {"Name" : ["Ü","K","F","D"],
           "Sports" : ["Basketball", "Football", "Tennis", "Running"],
            "Calories" : [190,90,400,210]
           }

In [101]:
frameinho3=pd.DataFrame(my_dicti3)

In [102]:
frameinho3

  Name      Sports  Calories
0    Ü  Basketball       190
1    K    Football        90
2    F      Tennis       400
3    D     Running       210

In [103]:
pd.concat([frameinho,frameinho2,frameinho3])

  Name      Sports  Calories
0    A  Basketball       100
1    B    Football       200
2    C      Tennis       300
3    D     Running       400
0    E  Basketball       150
1    Z    Football       290
2    Y      Tennis       310
3    N     Running       200
0    Ü  Basketball       190
1    K    Football        90
2    F      Tennis       400
3    D     Running       210

In [104]:
pd.merge(frameinho,frameinho2,on="Sports")

  Name_x      Sports  Calories_x Name_y  Calories_y
0      A  Basketball         100      E         150
1      B    Football         200      Z         290
2      C      Tennis         300      Y         310
3      D     Running         400      N         200